kubectl delete pod  argo-ui-6d6658d8f7-d62gh                           	      -n kubeflow
kubectl delete pod         centraldashboard-6f686c5b7c-gcjld           -n kubeflow
kubectl delete pod         jupyter-0                                  -n kubeflow
kubectl delete pod         jupyter-admin                            -n kubeflow
kubectl delete pod         jupyter-b                              -n kubeflow
kubectl delete pod         katib-ui-6c59754c48-7s7kp            -n kubeflow
kubectl delete pod         metacontroller-0                 -n kubeflow
kubectl delete pod         minio-d79b65988-7jr4c            -n kubeflow
kubectl delete pod         ml-pipelines-load-samples-lmgtz  -n kubeflow
kubectl delete pod         mysql-ffc889689-vddxk           -n kubeflow
kubectl delete pod         pytorch-operator-ff46f9b7d-nmqb5 -n kubeflow
kubectl delete pod         spartakus-volunteer-54f599d8b9-bs4vs     -n kubeflow
kubectl delete pod         tf-job-dashboard-7746db84cf-2w87r       -n kubeflow
kubectl delete pod         tf-job-operator-v1beta1-5949f668f7-wcbzk -n kubeflow
kubectl delete pod         vizier-core-7c56465f6-mn7hj             -n kubeflow
kubectl delete pod         vizier-core-rest-67f588b4cb-4dv2j      -n kubeflow
kubectl delete pod         vizier-db-86dc7d89c5-5mc8r            -n kubeflow
kubectl delete pod         vizier-suggestion-bayesianoptimization-7cb546fb84-lv2k4  -n kubeflow
kubectl delete pod         vizier-suggestion-grid-6587f9d6b-h82hh                  -n kubeflow
kubectl delete pod         vizier-suggestion-hyperband-8bb44f8c8-6b86b            -n kubeflow
kubectl delete pod         vizier-suggestion-random-7ff5db687b-wcjx6             -n kubeflow
kubectl delete pod         workflow-controller-cf79dfbff-rlgm8   -n kubeflow
